### ISSUE TITLE
Electron based mining application

### ISSUE THREAD

**Issue by sgerbino** [open-orchard/koinos-gui-miner#1]
As a potential crypto speculator, I would like an easy GUI based way to mine KOIN.

- [x] Create an electron application #2 
- [x] Add `koinos-miner` Node.js app as a dependency #3 
- [x] Provide GUI control to stop and start the mining #4 
- [x] Provide visual feedback for hashrate (realtime graph) and token balance #5 
- [x] Provide a checkbox for tipping the developer (OpenOrchard) #6 
- [x] Design a visually pleasing graphic user interface #7
