### ISSUE TITLE
Key Management

### ISSUE THREAD

**Issue by mvandeberg** [open-orchard/koinos-gui-miner#15]
As a Koinos Miner, I want to securely mine KOIN.

- [x] Local transaction signing via eth-lightwallet (#24)
- [x] Simple key management (generate keys locally and export) (#25)
- [x] Password prompt to unlock keys (#26)
- [x] Documentation on proper key management (hot/cold wallets) (#27)
