### ISSUE TITLE
UX Improvements

### ISSUE THREAD

**Issue by mvandeberg** [open-orchard/koinos-gui-miner#16]
As a Koinos Miner, I want an intuitive way to config the miner to mine at the desired difficulty.

- [x] Input Ethereum node endpoint (#28)
- [x] Input proof period (#29)
- [x] Window state management and config persistence (#30)
- [x] Handle and propagate important errors to the user in a pretty way (#31)
- [x] Display mining address' ETH balance and estimated mining "runway" (#32)
- [x] Save/load config on application close/launch (#33)
- [x] Document mining behavior so that user can intelligently input a proof period (#34)
- [x] Document (or link to documentation) on how to fund mining address (#35)
