### ISSUE TITLE
Miner Packaging

### ISSUE THREAD

**Issue by mvandeberg** [open-orchard/koinos-gui-miner#17]
As a Koinos user, I want to run the Koinos Miner on my OS.

- [x] Test GUI Miner in a Windows environment #19
- [x] Package Miner for *NIX natively #20
- [x] Travis CI scripts to package release tags for Mac OS & Linux #22
- [x] CI Packaging for Windows #23
